# Copyright 2015 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

sudo: false
language: go

go:
- 1.2
- 1.4.2

script:
- pre-commit-go
