# Copyright 2015 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

sudo: false
language: go

go:
- 1.4

# It's un necessary here since this code is testing pre-commit-go itself. If you
# copy-paste this file, un-comment the following lines.
#before_install:
#  - go get github.com/maruel/pre-commit-go

script:
  - pre-commit-go run -level 3
